title: ExinPool Help Center
description: ExinPool - node service
baseurl: ""
url: "https://exinpool.support"  

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings

theme: jekyll-theme-primer

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .gitignore
  - README.md
  - .DS_Store

relative_links:
  enabled: true
  collections: true
