title: ExinPool Help Center
description: ExinPool - node service
baseurl: ""
url: "https://exinpool.support"  
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
theme: jekyll-theme-primer

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .gitignore
  - README.md
  - .DS_Store

defaults:
  - scope:
      path: ""   
      type: "pages"
    values:
      order: 20
