title: ExinPool Help Center
description: ExinPool - node service
baseurl: ""
url: "https://www.exinpool.support"  

# Build settings
markdown: kramdown
encoding: UTF-8
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-readme-index
  - jekyll-github-metadata

theme: jekyll-theme-primer

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .gitignore
  - README.md
  - .DS_Store

relative_links:
  enabled: true
  collections: true

repository: exinpool/exinpool-support
