source "https://rubygems.org"

gem "jekyll", "~> 3.10.0"
gem "github-pages", "~> 232"
gem "webrick", "~> 1.8"
gem 'csv'
gem 'base64'

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17.0"
  gem "jekyll-seo-tag", "~> 2.8.0"
  gem "jekyll-theme-primer", "~> 0.6.0"
  gem "jekyll-relative-links"
  gem "jekyll-optional-front-matter"
  gem "jekyll-default-layout"
  gem "jekyll-titles-from-headings"
  gem "jekyll-readme-index"
  gem "jekyll-github-metadata"
end
