source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "webrick", "~> 1.8"
gem "jekyll-feed", "~> 0.17.0"
gem "jekyll-seo-tag", "~> 2.8.0"
gem "jekyll-theme-primer", "~> 0.6.0"
gem "kramdown-parser-gfm"
gem 'csv'
gem 'base64'

group :jekyll_plugins do
  gem "jekyll-relative-links"
  gem "jekyll-optional-front-matter"
  gem "jekyll-default-layout"
  gem "jekyll-titles-from-headings"
end
